// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	AccountCodes     string
	Accounts         string
	Ledgers          string
	SchemaMigrations string
	Transactions     string
}{
	AccountCodes:     "account_codes",
	Accounts:         "accounts",
	Ledgers:          "ledgers",
	SchemaMigrations: "schema_migrations",
	Transactions:     "transactions",
}
